// <auto-generated />
namespace BidOn.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EnitityAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnitityAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202103221526198_EnitityAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
